### ISSUE TITLE
Python error when running

### ISSUE THREAD

**Issue by GodsITguy** [doakey3/Subsimport#10]
I don't see if this version is compatible with version 3.2.0, but below is the error that I get when I try to import a SRT or TXT file.
Hoping you can help.
When I try to import SRT or TXT:

Python: Traceback (most recent call last):
  File "C:\Users\Tom\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Subsimport\operators\import_subtitles.py", line 78, in execute
    strips = subtitles_to_sequencer(context, subs)
  File "C:\Users\Tom\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Subsimport\operators\tools\subtitles_to_sequencer.py", line 36, in subtitles_to_sequencer
    text_strip = scene.sequence_editor.sequences.new_effect(
TypeError: SequencesTopLevel.new_effect(): error with keyword argument "frame_start" -  Function.frame_start expected an int type, not float

**Comment by doakey3** [comment]
Fixed. Please try it now.

**Comment by GodsITguy** [comment]
Thanks Daniel!  It works!  I'm kind of new to Git.  I just download the the
Zip from the green code button and pointed the blender add-on to that zip
instead of the subimport.zip file.  At first, I tried replacing the new
files inside the zip, and installing the addon but that didn't work.

Thanks again for the addon.  It's going to save me hours.
