### ISSUE TITLE
overlapping clips

### ISSUE THREAD

**Issue by GodsITguy** [doakey3/Subsimport#12]
When I import the .srt file that I'm creating with pytranscriber, it get overlapping text clips.  When I select the whole channel and move down the timeline, all overlapping clips snap to other available channels. I'm not getting an error, but I remember reading your instructions.  My source SRT files don't show overlapping times in the source file  I exported the SRT from Blender and it shows overlapping in miliseconds.

_"It is recommended that if you're making lyrics for songs that you increase the scene FPS to 100 or even 1000 frames per second before importing. The reason is that .srt files support time data down to the millisecond, but strips must conform to the scene's FPS value. If a low FPS is used, then the minimum timing difference will be limited by the scene FPS."
"Subimport does not allow any subtitles to overlap times and will automatically remove overlaps on import."_

I changed the frame rate to 120 and it still does it plus it's not deleting the overlapping clips (good thing) as the instructions note.

 Also, I noticed your version didn't change, but your source files did. Could you be so kind and post instructions on how to integrate these updates.  I just downloaded the master code and the zip from downloads and imported them both as separate add-on's Not sure if that was correct.

**Comment by yue-dongchen** [comment]
Seems to have been broken by a56464b. The start and end times in seconds should not be converted to integers before rounding. I will test it when I get to it.

**Comment by yue-dongchen** [comment]
Alright, that solves the issue. I will submit a pull request tomorrow.

**Comment by GodsITguy** [comment]
Thanks Yue. I'll wait to see the update posted to the repository.
