### ISSUE TITLE
Import *.txt doesn't import some lines

### ISSUE THREAD

**Issue by NathanLovato** [doakey3/Subsimport#3]
Importing txt files, even without any empty lines, skips some. I haven't looked into the code yet but I haven't noticed a particular pattern in the editor. You can see some text strips have double the regular size right after import:
![image](https://user-images.githubusercontent.com/12694995/32273531-1533e666-bf03-11e7-99c4-b98af266cda1.png)

Here's the source file:
[fibre-subtitles.txt](https://github.com/doakey3/Subsimport/files/1433992/fibre-subtitles.txt)

And thank you very much for your add-on! It's a real time saver. I also code a blender video editing add-on called [power sequencer](https://github.com/GDquest/Blender-power-sequencer/) so if you want me to I can look into the import code and do a PR.

**Comment by doakey3** [comment]
Thanks for reporting this. I think I fixed your issue. Give it a try!
