### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andrepazleal** [doakey3/Subsimport#4]
Hi, first thanks for the awesome addon, on Mojave and Blender 2.79 when trying to install it throws this error:

![image](https://user-images.githubusercontent.com/6593862/50243108-6892ef00-03b3-11e9-9136-3f67a759c30b.png)

**Comment by doakey3** [comment]
Looks like you're installing the 2.80 version on Blender 2.79. Remove this one completely, then download version 1.2.9 from the [releases](https://github.com/doakey3/Subsimport/releases) page for Blender 2.79 and try that one.

If you still have issues let me know.

**Comment by andrepazleal** [comment]
Nailed it, sorry to raise this ticket for this lack of attention.

**Comment by acebone** [comment]
Did the same thing - might I recommend that you add this info to the main-page?
